---
- name: uninstall nginx
  hosts: web
  become: true

  tasks:
  - name: remove the  epel-release repo
    yum:
      name: epel-release
      state: absent

  - name: remove the  nginx
    yum:
      name: nginx
      state: absent
